services:
  db:
    image: postgres:13
    container_name: odoo14-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:14
    container_name: odoo14-web
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "11014:8069"
      - "21014:8072"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./addons:/mnt/extra-addons

volumes:
  db-data:
